package com.leijx.newsapp.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.leijx.newsapp.bean.NewsChannelBean;

import com.leijx.newsapp.greendao.NewsChannelBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig newsChannelBeanDaoConfig;

    private final NewsChannelBeanDao newsChannelBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        newsChannelBeanDaoConfig = daoConfigMap.get(NewsChannelBeanDao.class).clone();
        newsChannelBeanDaoConfig.initIdentityScope(type);

        newsChannelBeanDao = new NewsChannelBeanDao(newsChannelBeanDaoConfig, this);

        registerDao(NewsChannelBean.class, newsChannelBeanDao);
    }
    
    public void clear() {
        newsChannelBeanDaoConfig.clearIdentityScope();
    }

    public NewsChannelBeanDao getNewsChannelBeanDao() {
        return newsChannelBeanDao;
    }

}
